output "instance-id" {
  value = aws_instance.webapp.id
}

output "name" {
  value = var.name
}

output "private-ip" {
  value = aws_instance.webapp.private_ip
}

output "public-ip" {
  value = aws_instance.webapp.public_ip
}

output "ssh_key" {
  description = "ssh key generated by terraform"
  value       = tls_private_key.my_key.private_key_pem
  sensitive = true
}