variable "aws-region" {
  default = "eu-central-1"
  type = string
  description = "Default region"
  sensitive = true
}
variable "ami-id" {
  default = { "eu-central-1" = "ami-015c25ad8763b2f11",
              "eu-west-1" = "ami-0d75513e7706cf2d9"
  } # AMI for an Ubuntu Server
  validation {
    condition = substr(var.ami-id, 0, 4) == "ami-"
    error_message = "Put an appropriate ami id "
  }
  type = map(string)
}

variable "generated_key_name" {
  type        = list(string)
  default     = ["aws_key_1", "aws-key-2", "aws-key-3"]
  description = "Key-pair generated by Terraform"
}

variable "iam-instance-profile" {
  default = ""
  type = string
}

variable "instance-type" {
  default = "t2.micro"
  type = string
}

variable "name" {
  default = "Simple Web App"
  type = string
}

variable "device-index" {
  default = 0
  type = number
}



