variable "aws-access-key" {
  type = string
  description = "My access key for Artem user"
  sensitive = true
}

variable "aws-secret-key" {
  type = string
  description = "My secret key for Artem user"
  sensitive = true
}

variable "aws-region" {
  default = "eu-central-1"
  type = string
  description = "Default region"
  sensitive = true
}
variable "ami-id" {
  default = "ami-015c25ad8763b2f11" # AMI for an Ubuntu Server for  region: eu-central-1
  validation {
    condition = substr(var.ami-id, 0, 4) == "ami-"
    error_message = "Put an appropriate ami id "
  }
  type = string
}

variable "generated_key_name" {
  type        = list(string)
  default     = ["aws_key_1", "aws-key-2", "aws-key-3"]
  description = "Key-pair generated by Terraform"
}

variable "iam-instance-profile" {
  default = ""
  type = string
}

variable "instance-type" {
  default = 't2.micro'
  type = string
}

variable "name" {
  default = "Simple Web App"
  type = string
}

variable "device-index" {
  default = 0
  type = number
}



